- name: Add firewalld rules
  firewalld:
    port: 2888/tcp
    permanent: yes
    state: enabled
  notify: Reload firewalld

- name: Add firewalld rules
  firewalld:
    port: 2181/tcp
    permanent: yes
    state: enabled
  notify: Reload firewalld

- name: Add firewalld rules
  firewalld:
    port: 3888/tcp
    permanent: yes
    state: enabled
  notify: Reload firewalld
