---
- name: Restart ZooKeeper service
  ansible.builtin.systemd:
    name: zookeeper.service
    state: restarted
    daemon_reload: yes
  when: zookeeper_restart

- name: Reload firewalld
  shell: firewall-cmd --reload
